### ISSUE TITLE
No audio on raspberry pi

### ISSUE THREAD

**Issue by Marius1342** [ThomasVon2021/Raspberry-HDMI-CSI-I2C#1]
Hello I try to use the I2C audio but i hear nothing on the recordings,I followed your installation instructions. Can i use the I2C as a normal microphone for the web browser?

**OS-> Linux raspberrypi 5.10.89-v7+
Board-> Raspberrypi 3b+
Chip-> C780**

**Comment by blikvm** [comment]
You can try the image and GStreamer commands we provide

**Comment by Marius1342** [comment]
Thanks
